title: ECG Codec
author: Shailesh Kumar

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - citations.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/shailesh1729/ecg-codec  # Online location of your book
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_repository_button: true

#parse:
myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  extra_extensions:
    - sphinx_proof
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
    - 'sphinx.ext.autosummary'
  config:
    bibtex_default_style: plain
    bibtex_reference_style: label
    mathjax3_config:
      tex:
        macros:
          "AA": "\\mathbb{A}"
          "BB": "\\mathbb{B}"
          "CC": "\\mathbb{C}"
          "DD": "\\mathbb{D}"
          "EE": "\\mathbb{E}"
          "FF": "\\mathbb{F}"
          "GG": "\\mathbb{G}"
          "HH": "\\mathbb{H}"
          "II": "\\mathbb{I}"
          "JJ": "\\mathbb{J}"
          "KK": "\\mathbb{K}"
          "LL": "\\mathbb{L}"
          "MM": "\\mathbb{M}"
          "NN": "\\mathbb{N}"
          "Nat": "\\mathbb{N}"
          "PP": "\\mathbb{P}"
          "QQ": "\\mathbb{Q}"
          "RR": "\\mathbb{R}"
          "RRMN": "\\mathbb{R}^{M \\times N}"
          "SS": "\\mathbb{S}"
          "TT": "\\mathbb{T}"
          "UU": "\\mathbb{U}"
          # A vector space
          "VV": "\\mathbb{V}"
          # A subspace
          "WW": "\\mathbb{W}"
          # An inner product space
          "XX": "\\mathbb{X}"
          "YY": "\\mathbb{Y}"
          # Integers
          "ZZ": "\\mathbb{Z}"
          "ZERO": "\\mathbf{O}"
          # Extended real line
          "ERL": "\\overline{\\mathbb{R}}"
          "RERL": "(-\\infty, \\infty]"
          "LERL": "[-\\infty, \\infty)"
          # All mathcal shortcuts
          "AAA": "\\mathcal{A}"
          "BBB": "\\mathcal{B}"
          "CCC": "\\mathcal{C}"
          "DDD": "\\mathcal{D}"
          "EEE": "\\mathcal{E}"
          "FFF": "\\mathcal{F}"
          "GGG": "\\mathcal{G}"
          "HHH": "\\mathcal{H}"
          "III": "\\mathcal{I}"
          "JJJ": "\\mathcal{J}"
          "KKK": "\\mathcal{K}"
          "LLL": "\\mathcal{L}"
          "MMM": "\\mathcal{M}"
          "NNN": "\\mathcal{N}"
          "OOO": "\\mathcal{O}"
          "PPP": "\\mathcal{P}"
          "QQQ": "\\mathcal{Q}"
          "RRR": "\\mathcal{R}"
          "SSS": "\\mathcal{S}"
          "TTT": "\\mathcal{T}"
          "UUU": "\\mathcal{U}"
          "VVV": "\\mathcal{V}"
          "WWW": "\\mathcal{W}"
          "XXX": "\\mathcal{X}"
          "YYY": "\\mathcal{Y}"
          "ZZZ": "\\mathcal{Z}"
          "Tau": "\\mathcal{T}"
          "Chi": "\\mathcal{X}"
          "Eta": "\\mathcal{H}"
          # Real part of a complex number
          "Re": "\\operatorname{Re}"
          "Im": "\\operatorname{Im}"
          # algorithm complexity
          "bigO": "\\mathcal{O}"
          "smallO": "\\mathcal{o}"
          # Null space
          "NullSpace": "\\mathcal{N}"
          # Column space
          "ColSpace": "\\mathcal{C}"
          # Row space
          "RowSpace": "\\mathcal{R}"
          # Power set
          "Power": "\\mathop{\\mathcal{P}}"
          "LinTSpace": "\\mathcal{L}"
          # Range
          "Range": "\\mathrm{R}"
          # image
          "Image": "\\mathrm{im}"
          # Kernel
          "Kernel": "\\mathrm{ker}"
          # Span
          "Span": "\\mathrm{span}"
          # Nullity of an operator
          "Nullity": "\\mathrm{nullity}"
          # Dimension of a vector space
          "Dim": "\\mathrm{dim}"
          # Rank of a matrix
          "Rank": "\\mathrm{rank}"
          # Trace of a matrix
          "Trace": "\\mathrm{tr}"
          # Diagonal of a matrix
          "Diag": "\\mathrm{diag}"
          "diag": "\\mathrm{diag}"
          # Signum function
          "sgn": "\\mathrm{sgn}"
          # Domain function
          "dom": "\\mathrm{dom}\\,"
          "range": "\\mathrm{range}\\,"
          "image": "\\mathrm{im}\\,"
          "nullspace": "\\mathrm{null}\\,"
          # Epigraph
          "epi": "\\mathrm{epi}\\,"
          # Hypograph
          "hypo": "\\mathrm{hypo}\\,"
          # Sublevel set
          "sublevel": "\\mathrm{sublevel}"
          # Superlevel set
          "superlevel": "\\mathrm{superlevel}"
          # Level set / Contour
          "contour": "\\mathrm{contour}"
          # Support function
          "supp": "\\mathrm{supp}"
          # Distance function
          "dist": "\\mathrm{dist}"
          # Similarity function
          "simf": "\\mathrm{sim}"
          # Optimum/optimal value
          "opt": "\\mathrm{opt}"
          # Success 
          "succ": "\\mathrm{succ}"
          # SNR 
          "snr": "\\mathrm{SNR}"
          # Reconstruction or Recovery SNR 
          "RSNR": "\\mbox{R-SNR}"
          # Percent Root Mean Square Difference
          "prd": "\\mathrm{PRD}"
          # Number of bits
          "bits": "\\mathrm{bits}"
          "bps": "\\mathrm{bps}"
          "bpm": "\\mathrm{bpm}"
          # Compression ratio
          "compr": "\\mathrm{CR}"
          # Measurement ratio
          "measurer": "\\mathrm{MR}"
          # Percentage space savings
          "pss": "\\mathrm{PSS}"
          # Percentage measurement savings
          "pms": "\\mathrm{PMS}"
          "nmse": "\\mathrm{NMSE}"
          "nrmse": "\\mathrm{N\_RMSE}"
          "window": "\\mathrm{window}"
          "flatten": "\\mathrm{flatten}"
          "clip": "\\mathrm{clip}"
          "round": "\\mathrm{round}"
          "ceiling": "\\mathrm{ceiling}"

          # Symmetric group
          "Sym": "\\mathrm{Sym}"
          "id" : "\\mathrm{id}"
          # Machine learning related stuff
          # ML
          "precision" : "\\mathrm{precision}"
          "recall" : "\\mathrm{recall}"
          "ML" : "\\mathbf{ML}"
          "MLE" : "\\mathbf{MLE}"
          "mah" : "\\mathbf{mah}"
          "chord" : "\\mathbf{chord}"
          "geo" : "\\mathbf{geo}"
          "nn" : "\\mathbf{nn}"
          "fn" : "\\mathbf{fn}"
          "ave" : "\\mathbf{ave}"
          "stat" : "\\mathbf{stat}"
          "mean" : "\\mathbf{mean}"
          "median" : "\\mathbf{median}"
          "mode" : "\\mathbf{mode}"



          # Row support
          "rowsupp": "\\mathop{\\mathrm{rowsupp}}"
          # Entry wise absolute value function
          "abs": "\\mathop{\\mathrm{abs}}"
          # error function
          "erf": "\\mathop{\\mathrm{erf}}"
          # complementary error function
          "erfc": "\\mathop{\\mathrm{erfc}}"
          # Sub Gaussian function
          "Sub": "\\mathop{\\mathrm{Sub}}"
          # Strictly sub Gaussian function
          "SSub": "\\mathop{\\mathrm{SSub}}"
          # Variance function
          "Var": "\\mathop{\\mathrm{Var}}"
          # Covariance matrix
          "Cov": "\\mathop{\\mathrm{Cov}}"
          # Affine hull of a set
          "AffineHull": "\\mathop{\\mathrm{aff}}"
          # Convex hull of a set
          "ConvexHull": "\\mathop{\\mathrm{conv}}"
          # Conic hull of a set
          "ConicHull": "\\mathop{\\mathrm{cone}}"
          # Set theory related stuff
          "argmin": "\\mathrm{arg}\\,\\mathrm{min}"
          "argmax": "\\mathrm{arg}\\,\\mathrm{max}"
          "EmptySet": "\\varnothing"
          "card": "\\mathrm{card}\\,"
          # Forall operator with some space
          "Forall": "\\; \\forall \\;"
          # such that
          "ST": "\\: | \\:"
          # Probability distributions
          "Gaussian": "\\mathcal{N}"
          # Sparse representations related stuff
          # Spark of a matrix
          "spark": "\\mathop{\\mathrm{spark}}"
          # Exact Recovery Criterion
          "ERC": "\\mathop{\\mathrm{ERC}}"
          # Maximum correlation
          "Maxcor": "\\mathop{\\mathrm{maxcor}}"
          # pseudo-inverse
          "dag": "\\dagger"
          # bracket operator
          "Bracket": "\\left [ \\; \\right ]"
          # infimal operator
          "infimal": "\\;\\square\\;"
          # OneVec
          "OneVec": "\\mathbf{1}"
          "ZeroVec": "\\mathbf{0}"
          "OneMat": "\\mathbb{1}"
          # Topology related stuff
          "Interior": ["\\mathring{#1}", 1]
          "Closure": ["\\overline{#1}", 1]
          "interior": "\\mathrm{int}\\,"
          "closure": "\\mathrm{cl}\\,"
          "boundary": "\\mathrm{bd}\\,"
          "frontier": "\\mathrm{fr}\\,"
          "diam": "\\mathrm{diam}\\,"
          "relint": "\\mathrm{ri}\\,"
          "relbd": "\\mathrm{relbd}\\,"
          "extreme": "\\mathrm{ext}\\,"
          "span": "\\mathrm{span}\\,"
          "affine": "\\mathrm{aff}\\,"
          "cone": "\\mathrm{cone}\\,"
          "convex": "\\mathrm{conv}\\,"
          "graph": "\\mathrm{gra}\\,"
          "kernel": "\\mathrm{ker}\\,"
          "dim": "\\mathrm{dim}\\,"
          "codim": "\\mathrm{codim}\\,"
          "nullity": "\\mathrm{nullity}\\,"
          "rank": "\\mathrm{rank}\\,"
          "prox": "\\mathrm{prox}"
          "best": "\\mathrm{best}"
          "ainterior": "\\mathrm{int}"
          "aclosure": "\\mathrm{cl}"
          "aboundary": "\\mathrm{bd}"
          "afrontier": "\\mathrm{fr}"
          "aextreme": "\\mathrm{ext}"
          # Thresholding operators
          "st": "\\mathrm{ST}"
          "ht": "\\mathrm{HT}"

          # boldface letters
          "bzero": "\\mathbf{0}"
          "bone": "\\mathbf{1}"
          "ba": "\\mathbf{a}"
          "bb": "\\mathbf{b}"
          "bc": "\\mathbf{c}"
          "bd": "\\mathbf{d}"
          "be": "\\mathbf{e}"
          "bf": "\\mathbf{f}"
          "bg": "\\mathbf{g}"
          "bh": "\\mathbf{h}"
          "bi": "\\mathbf{i}"
          "bj": "\\mathbf{j}"
          "bk": "\\mathbf{k}"
          "bl": "\\mathbf{l}"
          "bm": "\\mathbf{m}"
          "bn": "\\mathbf{n}"
          "bo": "\\mathbf{o}"
          "bp": "\\mathbf{p}"
          "bq": "\\mathbf{q}"
          "br": "\\mathbf{r}"
          "bs": "\\mathbf{s}"
          "bt": "\\mathbf{t}"
          "bu": "\\mathbf{u}"
          "bv": "\\mathbf{v}"
          "bw": "\\mathbf{w}"
          "bx": "\\mathbf{x}"
          "by": "\\mathbf{y}"
          "bz": "\\mathbf{z}"
          "bA": "\\mathbf{A}"
          "bB": "\\mathbf{B}"
          "bC": "\\mathbf{C}"
          "bD": "\\mathbf{D}"
          "bE": "\\mathbf{E}"
          "bF": "\\mathbf{F}"
          "bG": "\\mathbf{G}"
          "bH": "\\mathbf{H}"
          "bI": "\\mathbf{I}"
          "bJ": "\\mathbf{J}"
          "bK": "\\mathbf{K}"
          "bL": "\\mathbf{L}"
          "bM": "\\mathbf{M}"
          "bN": "\\mathbf{N}"
          "bO": "\\mathbf{O}"
          "bP": "\\mathbf{P}"
          "bQ": "\\mathbf{Q}"
          "bR": "\\mathbf{R}"
          "bS": "\\mathbf{S}"
          "bT": "\\mathbf{T}"
          "bU": "\\mathbf{U}"
          "bV": "\\mathbf{V}"
          "bW": "\\mathbf{W}"
          "bX": "\\mathbf{X}"
          "bY": "\\mathbf{Y}"
          "bZ": "\\mathbf{Z}"
          # Bold mathcal shortcuts
          "bAAA": "\\mathbf{\\mathcal{A}}"
          "bBBB": "\\mathbf{\\mathcal{B}}"
          "bCCC": "\\mathbf{\\mathcal{C}}"
          "bDDD": "\\mathbf{\\mathcal{D}}"
          "bEEE": "\\mathbf{\\mathcal{E}}"
          "bFFF": "\\mathbf{\\mathcal{F}}"
          "bGGG": "\\mathbf{\\mathcal{G}}"
          "bHHH": "\\mathbf{\\mathcal{H}}"
          "bIII": "\\mathbf{\\mathcal{I}}"
          "bJJJ": "\\mathbf{\\mathcal{J}}"
          "bKKK": "\\mathbf{\\mathcal{K}}"
          "bLLL": "\\mathbf{\\mathcal{L}}"
          "bMMM": "\\mathbf{\\mathcal{M}}"
          "bNNN": "\\mathbf{\\mathcal{N}}"
          "bOOO": "\\mathbf{\\mathcal{O}}"
          "bPPP": "\\mathbf{\\mathcal{P}}"
          "bQQQ": "\\mathbf{\\mathcal{Q}}"
          "bRRR": "\\mathbf{\\mathcal{R}}"
          "bSSS": "\\mathbf{\\mathcal{S}}"
          "bTTT": "\\mathbf{\\mathcal{T}}"
          "bUUU": "\\mathbf{\\mathcal{U}}"
          "bVVV": "\\mathbf{\\mathcal{V}}"
          "bWWW": "\\mathbf{\\mathcal{W}}"
          "bXXX": "\\mathbf{\\mathcal{X}}"
          "bYYY": "\\mathbf{\\mathcal{Y}}"
          "bZZZ": "\\mathbf{\\mathcal{Z}}"
          "Tau": "\\mathbf{\\mathcal{T}}"
          "Chi": "\\mathbf{\\mathcal{X}}"
          "Eta": "\\mathbf{\\mathcal{H}}"
          # Bold Greek letters
          "blambda": "\\pmb{\\lambda}"
